name: Deploy to GitHub Pages

on:
  # Настроено на пуш в ветки main и master
  push:
    branches: ["main", "master"]

  # Позволяет запускать этот workflow вручную во вкладке Actions
  workflow_dispatch:

# Устанавливаем права для токена GITHUB_TOKEN для публикации в GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешаем только одну конкурентную сборку
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
